name: Run Selenium Tests Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # This runs the tests every 10 minutes
  push:
    branches:
      - main  # Optionally, you can also trigger tests when changes are pushed to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Ensure this matches the Java version your project uses

      - name: Install dependencies
        run: |
          mvn install  # Install Maven dependencies if needed

      - name: Run Selenium BDD Tests
        run: |
          mvn test  # Adjust this if you're using a different command to run your tests
