name: Run Selenium Tests Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs the tests every 10 minutes
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'       # Specify the Java version you need
          distribution: 'adoptopenjdk'  # Use the valid distribution name

      - name: Install dependencies
        run: mvn install  # Install Maven dependencies

      - name: Run Selenium BDD Tests
        run: mvn test  # Run your tests
