name: Run Selenium Tests Every 10 Minutes

on:
  schedule:
    - cron: '0 0 */3 * *'  # Runs the tests every 3 days at midnight UTC
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version you need
          distribution: 'zulu'  # Use Zulu OpenJDK distribution

      - name: Install dependencies
        run: mvn install  # Install Maven dependencies

      - name: Run Selenium BDD Tests
        run: mvn test  # Run your tests

      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v4
        with:
         name: screenshots
         path: target/screenshots/*.png

  download:
    runs-on: ubuntu-latest
    needs: test  # This ensures the download job runs only after the 'test' job completes
    steps:
      - name: Download screenshots artifact
        uses: actions/download-artifact@v4
        with:
          name: screenshots  # Make sure this matches the name used in the upload step

      - name: List downloaded files
        run: ls -la
