name: Run Selenium Tests Every 10 Minutes

on:
  schedule:
    - cron: '0 0 */3 * *'  # Runs the tests every 3 days at midnight UTC
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify the Java version you need
          distribution: 'zulu'  # Use Zulu OpenJDK distribution

      - name: Install dependencies
        run: mvn install  # Install Maven dependencies

      - name: Run Selenium BDD Tests
        run: mvn test  # Run your tests

      - name: Create test file
        run: echo "Test file for artifact upload" > target/screenshots/test.txt

      - name: Upload test file as artifact
        uses: actions/upload-artifact@v2
        with:
         name: test-artifact
         path: target/screenshots/test.txt
